config/routes.rb
Rails.application.routes.draw do
  resources :tags
  devise_for :users, controllers: {registrations: 'users/registrations'}

  resources :books, except: :index
  resources :tags, except: :show

  get '/books/:id/read/:page(.:format)' => 'books#read', as: 'read'
  root 'pages#main'
  get 'home' => 'pages#home'
  get 'adm_users' => 'pages#adm_users'
  get 'error' => 'pages#error'
  get 'private' => 'pages#private'
  get 'delete_user' => 'pages#delete_user'
  get 'feedback' => 'pages#feedback'

  get '/books/:id/send_book' => 'books#email_book', as: 'email_book'

  get 'publiclib' => 'pages#publiclib'

  patch 'books/:id/convert(.:format)' => 'books#convert', as: 'convert'
  patch 'books/:id/add_tag(.:format)' => 'books#add_tag', as: 'add_tag'
  patch 'books/:id/remove_tag(.:format)' => 'books#remove_tag', as: 'remove_tag'
  post 'books/:id(.:format)' => 'books#add_book', as: 'add_book'

end

app/views/pages/error.html.erb
<div class="jumbotron">
  <div class="container">
    <h1>BookStream</h1>
    <p class="lead" id="notice"><%= notice %>
      </p>
    <p>You must <%= link_to('Log In', new_user_session_path)  %> or <%= link_to "Sign Up", new_registration_path(:user) %> first.</p>
  </div>
</div> 

app/views/pages/feedback.html.erb
<div class="jumbotron">

  <center><iframe src="https://docs.google.com/forms/d/1SjSyH53e_JuovotuRxFPyuVWATz3qK87gWWBiKhRod0/viewform?embedded=true"
     width="760" height="1080" frameborder="0" marginheight="0" marginwidth="0">Cargando...</iframe></center>
</div>

app/views/pages/home.html.erb
<style>
.row {
  display: -webkit-box;
  display: -webkit-flex;
  display: -ms-flexbox;
  display:         flex;
  flex-wrap: wrap;
}
.row > [class*='col-'] {
  display: flex;
  flex-direction: column;
}
img {
  margin-bottom: -15px;
  width: 304px;
  height: 365px;
  max-width: 100%;
  max-height: 100%;
  display: block;
}

p.ex {
  width: 330px;
  padding-left: 28px;
}
img.bookdefault {
  width: 100%;
  height: 436px;
  max-width: 100%;
  max-height: 100%;
  margin: 0px -20px -15px -20px;
  display: block;
}

</style>

<div class="jumbotron">
  <div class="container">
    <div class="col-md-8">
      <h1>BookStream</h1>
      <% if current_user.email != 'bookstreammailer@gmail.com' %>
        <p>Hi <big><strong><%= current_user.name %></strong></big>, this is your library!</p>
      <% else %>
        <p>Hi <big><strong>BookStream Administrator</strong></big> (ID #<%= current_user.id %>), here are all the books in the DB.</p>
      <% end %>
    </div>
    <div class="col-md-4">
      <%= link_to 'Public Library', publiclib_path, class: "btn btn-lg btn-danger pull-right" %>
      <br></br><br></br>
      <a href='/books/new' button type="button" class="btn btn-lg btn-primary pull-right"><span class="glyphicon glyphicon-cloud-upload"></span> Upload New Book</button></a>
    </div>
  </div>
</div>

<% if current_user.email != 'bookstreammailer@gmail.com'
  if defined?(@search)
    books_searched=[]
    if current_user.books.size != 0
      current_user.books.each do |b|
        if b.name.downcase.include? @search.downcase
          books_searched.insert(-1, b)
        end
        if b.author.downcase.include? @search.downcase
          books_searched.insert(-1, b)
        end
        if b.tags.size != 0
          b.tags.each do |f|
            if f.name.downcase.include? @search.downcase
              books_searched.insert(-1, b)
            end
          end
        end
        if b.description.downcase.include? @search.downcase
          books_searched.insert(-1, b)
        end
        if b.document_file_name.downcase.include? @search.downcase
          books_searched.insert(-1, b)
        end
        if b.image_file_name != nil
          if b.image_file_name.downcase.include? @search.downcase
            books_searched.insert(-1, b)
          end
        end
      end
    end
    if current_user.books.size == 0 %>
      <div class="alert alert-danger" role="alert">
         <strong>You don't have books!</strong> Try to <%= link_to('upload', new_book_path) %> a new book.
      </div>
      <br>
    <% else %>
      <div class="container">
        <% if books_searched.uniq.size == 0 %>
          <div class="alert alert-danger" role="alert">
           <strong>No results for your search.</strong> You might find it in the <%= link_to('Public Library', publiclib_path) %>.
          </div>
        <% else %>
          <div class="row">
            <% books_searched.uniq.each do |f| %>
              <div class="col-md-3 col-xs-12">
                <center><h3 style="margin-bottom:-8px"><%=f.name%> </h3>
                <h6>by <%=f.author%> <br/></h6>
                <% if f.tags.size != 0 %>
                <% f.tags.each do |f| %>
                  <a style="color:<%=f.color%>" href="/tags"><span class="glyphicon glyphicon-tag"></span> <%=f.name%> </a>
                <% end %> <br/>
              <% end %></center>
                <% if f.image_file_name != nil %>
                  <center class="book_image"><%= image_tag(f.image, size: "304x436", :alt => "rss feed") %></center>
                <% else %>
                  <center class="book_image"><img class="bookdefault" src="http://icons.iconarchive.com/icons/paomedia/small-n-flat/1024/book-bookmark-icon.png"></center>
                <% end %>
                <br>
                <p class="ex" align="justify"> <%=f.description%> <br/> </p>
                <center><p><big><td><%= link_to '<span class="glyphicon glyphicon-book"></span> Show Book'.html_safe , f , class: "btn btn-success", style: "margin-bottom:10px" %></td></big></p></center>
              </div>
            <% end %>
          </div>
        <% end %>
      </div>
    <%end%>
  <% else %>
    <% if current_user.books.size == 0 %>
      <div class="alert alert-danger" role="alert">
        <strong>You don't have books!</strong> Try to <%= link_to('upload', new_book_path)  %> a new book.
      </div>
      <br>
    <% else %>
      <div class="container">
        <div class="row">
          <% current_user.books.each do |f| %>
            <div class="col-md-3 col-xs-12">
              <center><h3 style="margin-bottom:-8px"><%=f.name%> </h3>
              <h6>by <%=f.author%> <br/></h6>
              <% if f.tags.size != 0 %>
                <% f.tags.each do |f| %>
                  <a style="color:<%=f.color%>" href="/tags"><span class="glyphicon glyphicon-tag"></span> <%=f.name%> </a>
                <% end %> <br/>
              <% end %></center>
              <% if f.image_file_name != nil %>
                <center class="book_image"><%= image_tag(f.image, size: "304x436", :alt => "rss feed") %></center>
              <% else %>
                <center class="book_image"><img class="bookdefault" src="http://icons.iconarchive.com/icons/paomedia/small-n-flat/1024/book-bookmark-icon.png"></center>
              <%end%>
              <br>
              <p class="ex" align="justify"> <%=f.description%> <br/> </p>
              <center><p><big><td><%= link_to '<span class="glyphicon glyphicon-book"></span> Show Book'.html_safe , f , class: "btn btn-success", style: "margin-bottom:10px" %></td></big></p></center>
            </div>
          <% end %>
        </div>
      </div>
    <%end%>
  <% end %>
<% else %>
  <% if defined?(@search)
    books_searched=[]
    if Book.all.size != 0
      Book.all.each do |b|
        if b.name.downcase.include? @search.downcase
          books_searched.insert(-1, b)
        end
        if b.author.downcase.include? @search.downcase
          books_searched.insert(-1, b)
        end
        if b.tags.size != 0
          b.tags.each do |f|
            if f.name.downcase.include? @search.downcase
              books_searched.insert(-1, b)
            end
          end
        end
        if b.description.downcase.include? @search.downcase
          books_searched.insert(-1, b)
        end
        if b.document_file_name.downcase.include? @search.downcase
          books_searched.insert(-1, b)
        end
        if b.image_file_name != nil
          if b.image_file_name.downcase.include? @search.downcase
            books_searched.insert(-1, b)
          end
        end
        if ('user #' + b.user_id.to_s).downcase.include? @search.downcase
          books_searched.insert(-1, b)
        end
        if ('book #' + b.id.to_s).downcase.include? @search.downcase
          books_searched.insert(-1, b)
        end
        if b.access.downcase.include? @search.downcase
          books_searched.insert(-1, b)
        end
        if b.user != nil
          if b.user.name.downcase.include? @search.downcase
            books_searched.insert(-1, b)
          end
          if b.user.last_name.downcase.include? @search.downcase
            books_searched.insert(-1, b)
          end
          if b.user.email.downcase.include? @search.downcase
            books_searched.insert(-1, b)
          end
        end
      end
    end
    if Book.all.size == 0 %>
      <div class="alert alert-danger" role="alert">
        <strong>You don't have books!</strong> Try to <%= link_to('upload', new_book_path) %> a new book.
      </div>
      <br>
    <% else %>
      <div class="container">
        <% if books_searched.uniq.size == 0 %>
          <div class="alert alert-danger" role="alert">
            <strong>No results for your search.</strong>
          </div>
        <% else %>
          <div class="row">
            <% books_searched.uniq.each do |f| %>
              <div class="col-md-3 col-xs-12">
                <center><h3 style="margin-bottom:-8px"><%=f.name%> </h3>
                <h6>by <%=f.author%> <br/></h6>
                <% if f.tags.size != 0 %>
                <% f.tags.each do |f| %>
                  <a style="color:<%=f.color%>" href="/tags"><span class="glyphicon glyphicon-tag"></span> <%=f.name%> </a>
                <% end %> <br/>
              <% end %>
                <%= f.access %> book, #<%= f.id %> (<%= f.document_file_name.split(".").last %>)<br/>
                <% if f.user != nil %>
                  User #<%= f.user_id %>, <%= f.user.name %> <%= f.user.last_name %>
                <% end %></center>
                <% if f.image_file_name != nil %>
                  <center class="book_image"><%= image_tag(f.image, size: "304x436", :alt => "rss feed") %></center>
                <% else %>
                  <center class="book_image"><img class="bookdefault" src="http://icons.iconarchive.com/icons/paomedia/small-n-flat/1024/book-bookmark-icon.png"></center>
                <% end %>
                <br>
                <p class="ex" align="justify"> <%=f.description%> </p>
                <center><%= link_to '<span class="glyphicon glyphicon-book"></span> Show Book'.html_safe , f , class: "btn btn-success", style: "margin-bottom:10px" %> <%= link_to '<span class="glyphicon glyphicon-pencil"></span>'.html_safe, edit_book_path(f), class: "btn btn-warning", style: "margin-bottom:10px" %> <%= link_to '<span class="glyphicon glyphicon-trash"></span>'.html_safe, f, method: :delete, class: "btn btn-danger", style: "margin-bottom:10px" %></center>
              </div>
            <%end%>
          </div>
        <%end%>
      </div>
    <% end %>
  <% else %>
    <% if Book.all.size == 0 %>
      <div class="alert alert-danger" role="alert">
         <strong>You don't have books!</strong> Try to <%= link_to('upload', new_book_path)  %> a new book.
       </div>
      <br>
    <% else %>
      <div class="container">
        <div class="row">
          <% Book.all.each do |f| %>
            <div class="col-md-3 col-xs-12">
              <center><h3 style="margin-bottom:-8px"><%=f.name%> </h3></center>
              <center><h6>by <%=f.author%> <br/></h6>
              <% if f.tags.size != 0 %>
                <% f.tags.each do |f| %>
                  <a style="color:<%=f.color%>" href="/tags"><span class="glyphicon glyphicon-tag"></span> <%=f.name%> </a>
                <% end %> <br/>
              <% end %>
              <%= f.access %> book, #<%= f.id %> (<%= f.document_file_name.split(".").last %>)<br/>
              <% if f.user != nil %>
                User #<%= f.user_id %>, <%= f.user.name %> <%= f.user.last_name %>
              <% end %></center>
              <% if f.image_file_name != nil %>
                <center class="book_image"><%= image_tag(f.image, size: "304x436", :alt => "rss feed") %></center>
              <% else %>
                <center class="book_image"><img class="bookdefault" src="http://icons.iconarchive.com/icons/paomedia/small-n-flat/1024/book-bookmark-icon.png" ></center>
              <%end%>
              <br>
              <p class="ex" align="justify"> <%=f.description%> </p>
              <center><%= link_to '<span class="glyphicon glyphicon-book"></span> Show Book'.html_safe , f , class: "btn btn-success", style: "margin-bottom:10px" %> <%= link_to '<span class="glyphicon glyphicon-pencil"></span>'.html_safe, edit_book_path(f), class: "btn btn-warning", style: "margin-bottom:10px" %> <%= link_to '<span class="glyphicon glyphicon-trash"></span>'.html_safe, f, method: :delete, class: "btn btn-danger", style: "margin-bottom:10px" %></center>
            </div>
          <% end %>
        </div>
      </div>
    <% end %>
  <% end %>
<% end %>

<div class="jumbotron">
  <div class="container">
    <center><h2>Manage your tags</h2></center>
    <a href='/tags/new' button type="button" class="btn btn-lg btn-danger pull-left"><span class="glyphicon glyphicon-tags"></span>  Add tags</a>
    <a href='/tags' button type="button" class="btn btn-lg btn-primary pull-right"><span class="glyphicon glyphicon-pencil"></span> Edit tags</a>
  </div>
</div>

app/views/pages/homebig.html.erb
<style>
.row {
  display: -webkit-box;
  display: -webkit-flex;
  display: -ms-flexbox;
  display:         flex;
  flex-wrap: wrap;
}
.row > [class*='col-'] {
  display: flex;
  flex-direction: column;
}
img {
  margin-bottom: -15px;
  width: 304px;
  height: 436px;
  max-width: 100%;
  max-height: 100%;
  display: block;
}

p.ex {
  width: 330px;
  padding-left: 28px;
}
img.bookdefault {
  width: 100%;
  height: 436px;
  max-width: 100%;
  max-height: 100%;
  margin: 0px -20px -15px -20px;
  display: block;
}

</style>

<div class="jumbotron">
  <div class="container">
    <div class="col-md-8">
      <h1>BookStream</h1>
      <% if current_user.email != 'bookstreammailer@gmail.com' %>
        <p>Hi <big><strong><%= current_user.name %></strong></big>, this is your library!</p>
      <% else %>
        <p>Hi <big><strong>BookStream Administrator</strong></big> (ID #<%= current_user.id %>), here are all the books in the DB.</p>
      <% end %>
    </div>
    <div class="col-md-4">
      <%= link_to 'Public Library', publiclib_path, class: "btn btn-lg btn-danger pull-right" %>
      <br></br><br></br>
      <a href='/books/new' button type="button" class="btn btn-lg btn-primary pull-right"><span class="glyphicon glyphicon-cloud-upload"></span> Upload New Book</button></a>
    </div>
  </div>
</div>

<% if current_user.email != 'bookstreammailer@gmail.com'
  if defined?(@search)
    books_searched=[]
    if current_user.books.size != 0
      current_user.books.each do |b|
        if b.name.downcase.include? @search.downcase
          books_searched.insert(-1, b)
        end
        if b.author.downcase.include? @search.downcase
          books_searched.insert(-1, b)
        end
        if b.tags.size != 0
          b.tags.each do |f|
            if f.name.downcase.include? @search.downcase
              books_searched.insert(-1, b)
            end
          end
        end
        if b.description.downcase.include? @search.downcase
          books_searched.insert(-1, b)
        end
        if b.document_file_name.downcase.include? @search.downcase
          books_searched.insert(-1, b)
        end
        if b.image_file_name != nil
          if b.image_file_name.downcase.include? @search.downcase
            books_searched.insert(-1, b)
          end
        end
      end
    end
    if current_user.books.size == 0 %>
      <div class="alert alert-danger" role="alert">
         <strong>You don't have books!</strong> Try to <%= link_to('upload', new_book_path) %> a new book.
      </div>
      <br>
    <% else %>
      <div class="container">
        <% if books_searched.uniq.size == 0 %>
          <div class="alert alert-danger" role="alert">
           <strong>No results for your search.</strong> You might find it in the <%= link_to('Public Library', publiclib_path) %>.
          </div>
        <% else %>
          <div class="row">
            <% books_searched.uniq.each do |f| %>
              <div class="col-md-4">
                <center><h2 style="margin-bottom:-8px"><%=f.name%> </h2>
                <h5>by <%=f.author%> <br/></h5>
                <% if f.tags.size != 0 %>
                <% f.tags.each do |f| %>
                  <a style="color:<%=f.color%>" href="/tags"><span class="glyphicon glyphicon-tag"></span> <%=f.name%> </a>
                <% end %> <br/>
              <% end %></center>
                <% if f.image_file_name != nil %>
                  <center class="book_image"><%= image_tag(f.image, size: "304x436", :alt => "rss feed") %></center>
                <% else %>
                  <center class="book_image"><img class="bookdefault" src="http://icons.iconarchive.com/icons/paomedia/small-n-flat/1024/book-bookmark-icon.png"></center>
                <% end %>
                <br>
                <p class="ex" align="justify"> <%=f.description%> <br/> </p>
                <center><p><big><td><%= link_to '<span class="glyphicon glyphicon-book"></span> Show Book'.html_safe , f , class: "btn btn-success", style: "margin-bottom:10px" %></td></big></p></center>
              </div>
            <% end %>
          </div>
        <% end %>
      </div>
    <%end%>
  <% else %>
    <% if current_user.books.size == 0 %>
      <div class="alert alert-danger" role="alert">
        <strong>You don't have books!</strong> Try to <%= link_to('upload', new_book_path)  %> a new book.
      </div>
      <br>
    <% else %>
      <div class="container">
        <div class="row">
          <% current_user.books.each do |f| %>
            <div class="col-md-4">
              <center><h2 style="margin-bottom:-8px"><%=f.name%> </h2>
              <h5>by <%=f.author%> <br/></h5>
              <% if f.tags.size != 0 %>
                <% f.tags.each do |f| %>
                  <a style="color:<%=f.color%>" href="/tags"><span class="glyphicon glyphicon-tag"></span> <%=f.name%> </a>
                <% end %> <br/>
              <% end %></center>
              <% if f.image_file_name != nil %>
                <center class="book_image"><%= image_tag(f.image, size: "304x436", :alt => "rss feed") %></center>
              <% else %>
                <center class="book_image"><img class="bookdefault" src="http://icons.iconarchive.com/icons/paomedia/small-n-flat/1024/book-bookmark-icon.png"></center>
              <%end%>
              <br>
              <p class="ex" align="justify"> <%=f.description%> <br/> </p>
              <center><p><big><td><%= link_to '<span class="glyphicon glyphicon-book"></span> Show Book'.html_safe , f , class: "btn btn-success", style: "margin-bottom:10px" %></td></big></p></center>
            </div>
          <% end %>
        </div>
      </div>
    <%end%>
  <% end %>
<% else %>
  <% if defined?(@search)
    books_searched=[]
    if Book.all.size != 0
      Book.all.each do |b|
        if b.name.downcase.include? @search.downcase
          books_searched.insert(-1, b)
        end
        if b.author.downcase.include? @search.downcase
          books_searched.insert(-1, b)
        end
        if b.tags.size != 0
          b.tags.each do |f|
            if f.name.downcase.include? @search.downcase
              books_searched.insert(-1, b)
            end
          end
        end
        if b.description.downcase.include? @search.downcase
          books_searched.insert(-1, b)
        end
        if b.document_file_name.downcase.include? @search.downcase
          books_searched.insert(-1, b)
        end
        if b.image_file_name != nil
          if b.image_file_name.downcase.include? @search.downcase
            books_searched.insert(-1, b)
          end
        end
        if ('user #' + b.user_id.to_s).downcase.include? @search.downcase
          books_searched.insert(-1, b)
        end
        if ('book #' + b.id.to_s).downcase.include? @search.downcase
          books_searched.insert(-1, b)
        end
        if b.access.downcase.include? @search.downcase
          books_searched.insert(-1, b)
        end
        if b.user != nil
          if b.user.name.downcase.include? @search.downcase
            books_searched.insert(-1, b)
          end
          if b.user.last_name.downcase.include? @search.downcase
            books_searched.insert(-1, b)
          end
          if b.user.email.downcase.include? @search.downcase
            books_searched.insert(-1, b)
          end
        end
      end
    end
    if Book.all.size == 0 %>
      <div class="alert alert-danger" role="alert">
        <strong>You don't have books!</strong> Try to <%= link_to('upload', new_book_path) %> a new book.
      </div>
      <br>
    <% else %>
      <div class="container">
        <% if books_searched.uniq.size == 0 %>
          <div class="alert alert-danger" role="alert">
            <strong>No results for your search.</strong>
          </div>
        <% else %>
          <div class="row">
            <% books_searched.uniq.each do |f| %>
              <div class="col-md-4">
                <center><h2 style="margin-bottom:-8px"><%=f.name%> </h2>
                <h5>by <%=f.author%> <br/></h5>
                <% if f.tags.size != 0 %>
                <% f.tags.each do |f| %>
                  <a style="color:<%=f.color%>" href="/tags"><span class="glyphicon glyphicon-tag"></span> <%=f.name%> </a>
                <% end %> <br/>
              <% end %>
                <%= f.access %> book, #<%= f.id %> (<%= f.document_file_name.split(".").last %>)<br/>
                <% if f.user != nil %>
                  User #<%= f.user_id %>, <%= f.user.name %> <%= f.user.last_name %>
                <% end %></center>
                <% if f.image_file_name != nil %>
                  <center class="book_image"><%= image_tag(f.image, size: "304x436", :alt => "rss feed") %></center>
                <% else %>
                  <center class="book_image"><img class="bookdefault" src="http://icons.iconarchive.com/icons/paomedia/small-n-flat/1024/book-bookmark-icon.png"></center>
                <% end %>
                <br>
                <p class="ex" align="justify"> <%=f.description%> </p>
                <center><%= link_to '<span class="glyphicon glyphicon-book"></span> Show Book'.html_safe , f , class: "btn btn-success", style: "margin-bottom:10px" %> <%= link_to '<span class="glyphicon glyphicon-pencil"></span>'.html_safe, edit_book_path(f), class: "btn btn-warning", style: "margin-bottom:10px" %> <%= link_to '<span class="glyphicon glyphicon-trash"></span>'.html_safe, f, method: :delete, class: "btn btn-danger", style: "margin-bottom:10px" %></center>
              </div>
            <%end%>
          </div>
        <%end%>
      </div>
    <% end %>
  <% else %>
    <% if Book.all.size == 0 %>
      <div class="alert alert-danger" role="alert">
         <strong>You don't have books!</strong> Try to <%= link_to('upload', new_book_path)  %> a new book.
       </div>
      <br>
    <% else %>
      <div class="container">
        <div class="row">
          <% Book.all.each do |f| %>
            <div class="col-md-4">
              <center><h2 style="margin-bottom:-8px"><%=f.name%> </h2></center>
              <center><h5>by <%=f.author%> <br/></h5>
              <% if f.tags.size != 0 %>
                <% f.tags.each do |f| %>
                  <a style="color:<%=f.color%>" href="/tags"><span class="glyphicon glyphicon-tag"></span> <%=f.name%> </a>
                <% end %> <br/>
              <% end %>
              <%= f.access %> book, #<%= f.id %> (<%= f.document_file_name.split(".").last %>)<br/>
              <% if f.user != nil %>
                User #<%= f.user_id %>, <%= f.user.name %> <%= f.user.last_name %>
              <% end %></center>
              <% if f.image_file_name != nil %>
                <center class="book_image"><%= image_tag(f.image, size: "304x436", :alt => "rss feed") %></center>
              <% else %>
                <center class="book_image"><img class="bookdefault" src="http://icons.iconarchive.com/icons/paomedia/small-n-flat/1024/book-bookmark-icon.png" ></center>
              <%end%>
              <br>
              <p class="ex" align="justify"> <%=f.description%> </p>
              <center><%= link_to '<span class="glyphicon glyphicon-book"></span> Show Book'.html_safe , f , class: "btn btn-success", style: "margin-bottom:10px" %> <%= link_to '<span class="glyphicon glyphicon-pencil"></span>'.html_safe, edit_book_path(f), class: "btn btn-warning", style: "margin-bottom:10px" %> <%= link_to '<span class="glyphicon glyphicon-trash"></span>'.html_safe, f, method: :delete, class: "btn btn-danger", style: "margin-bottom:10px" %></center>
            </div>
          <% end %>
        </div>
      </div>
    <% end %>
  <% end %>
<% end %>

<div class="jumbotron">
  <div class="container">
    <center><h2>Manage your tags</h2></center>
    <a href='/tags/new' button type="button" class="btn btn-lg btn-danger pull-left"><span class="glyphicon glyphicon-tags"></span>  Add tags</a>
    <a href='/tags' button type="button" class="btn btn-lg btn-primary pull-right"><span class="glyphicon glyphicon-pencil"></span> Edit tags</a>
  </div>
</div>

app/views/pages/main.html.erb
    <div class="jumbotron">
      <div class="container">
        <h1>BookStream</h1>
        <p>Forget about carrying extra weight, let us save your stories.</p>
        <a href="https://github.com/IIC2143-2016-1/bookstream">Learn More</a>
      </div>
    </div> 

    <div class="row">
        <img class = "col-md-12" height="400" src="https://upload.wikimedia.org/wikipedia/commons/7/76/Urval_av_de_bocker_som_har_vunnit_Nordiska_radets_litteraturpris_under_de_50_ar_som_priset_funnits_%282%29.jpg" >
    </div>

app/views/pages/private.html.erb
<div class="jumbotron">
  <div class="container">
    <h1>BookStream</h1>
    <div id="error_explanation">
    	<p class="lead" id="notice"><span class="glyphicon glyphicon-exclamation-sign" aria-hidden="true"></span> <%= notice %>
      </p>
      </div>
  </div>
</div> 