config/routes.rb
Rails.application.routes.draw do
  resources :tags
  devise_for :users, controllers: {registrations: 'users/registrations'}

  resources :books, except: :index
  resources :tags, except: :show

  get '/books/:id/read/:page(.:format)' => 'books#read', as: 'read'
  root 'pages#main'
  get 'home' => 'pages#home'
  get 'adm_users' => 'pages#adm_users'
  get 'error' => 'pages#error'
  get 'private' => 'pages#private'
  get 'delete_user' => 'pages#delete_user'
  get 'feedback' => 'pages#feedback'

  get '/books/:id/send_book' => 'books#email_book', as: 'email_book'

  get 'publiclib' => 'pages#publiclib'

  patch 'books/:id/convert(.:format)' => 'books#convert', as: 'convert'
  patch 'books/:id/add_tag(.:format)' => 'books#add_tag', as: 'add_tag'
  patch 'books/:id/remove_tag(.:format)' => 'books#remove_tag', as: 'remove_tag'
  post 'books/:id(.:format)' => 'books#add_book', as: 'add_book'

end

app/models/book.rb
class Book < ActiveRecord::Base
    validates :name, presence: true
    validates :author, presence: true
    validates :access, presence: true
    has_attached_file :document, {preserve_files: true}
    validates_attachment :document, presence: true
    validates_attachment_file_name :document, matches: [/pdf\Z/, /mobi\Z/, /epub\Z/, /azw\Z/]
    belongs_to :user
    has_attached_file :image, {preserve_files: true}
    validates_attachment_content_type :image, content_type: /\Aimage\/.*\Z/
    has_and_belongs_to_many :tags

end

app/controllers/books_controller.rb
class BooksController < ApplicationController

  before_action :set_book, only: [:show, :edit, :update, :destroy, :add_tag, :read, :add_book, :email_book, :convert, :remove_tag]

  before_action :authenticate_user!
  before_action :set_path, only: [:read, :email_book]
  before_action :googleapi, only: [:show]
  before_action :imbdapi, only: [:show]

  require 'will_paginate/array'

  # GET /books
  # GET /books.json

  # GET /books/1
  # GET /books/1.json

  def convert
    convert_book(params.require(:book).permit(:format)[:format])
    redirect_to @download_url
  end

  def show
    if current_user.email != 'bookstreammailer@gmail.com'
      if not current_user.books.include? @book
        redirect_to '/home'
      end
    end
  end

  def email_book
    call_rake :email_book, {:USER => current_user.id, :BOOK => @book.id}
    respond_to do |format|
      format.html { redirect_to @book, notice: 'Sending email' }
    end
  end

  # GET /books/1/read
  def read
    if @book.document_file_name.split(".").last.downcase == "pdf"
      @path = (Rails.root.to_s + "/public" + @book.document.url).split('?').first
    else
      @path = Rails.root.to_s + "/public/tempdf/B#{@book.id}.pdf"
      if not File.exist? File.expand_path @path
        convert_book("pdf")
        require 'open-uri'
        open(@path, 'wb') do |file|
          file << open(@download_url).read
        end
      end
    end
    @reader = PDF::Reader.new(@path)
    #@data = @reader.pages
    @data = @reader.pages[1..-1]
    @page = params[:page].to_i
    #@all_data = @reader.pages[1..-1]
    #@all_data = @reader.pages
    #@data = Array.new
    #@data.each do |p|
    #  if p.text.length < 15
    #    @data.delete(p)
    #  end
    #end
    #@pages = @data.paginate(:page => params[:page], :per_page => 1)
  end


  # GET /books/new
  def new
    @book = Book.new
  end

  # GET /books/1/edit
  def edit
    if current_user.email != 'bookstreammailer@gmail.com'
      if not current_user.books.include? @book
        redirect_to '/home'
      end
    end
  end

  # POST /books
  # POST /books.json
  def create
    @book = Book.new(book_params)
    respond_to do |format|
      if @book.save
        if @book.access == "Public"
          @book = Book.new(book_params)
          @book.access = "Private"
        end
        current_user.books << @book
        @book.save
        format.html { redirect_to @book, notice: 'Book was successfully created.' }
        format.json { render :show, status: :created, location: @book }
      else
        format.html { render :new }
        format.json { render json: @book.errors, status: :unprocessable_entity }
      end
    end
  end

  # PATCH/PUT /books/1
  # PATCH/PUT /books/1.json
  def update
    respond_to do |format|
      if @book.update(book_params)
        format.html { redirect_to @book, notice: 'Book was successfully updated.' }
        format.json { render :show, status: :ok, location: @book }
      else
        format.html { render :edit }
        format.json { render json: @book.errors, status: :unprocessable_entity }
      end
    end
  end

  # DELETE /books/1
  # DELETE /books/1.json
  def destroy
    @book.delete
    respond_to do |format|
      format.html { redirect_to home_path, notice: '' }
      format.json { head :no_content }
    end
  end

  def add_tag
    @tag_name = params.require(:book).permit(:tags)
    @tag = Tag.find_by(name: @tag_name[:tags])
    if not @book.tags.include? @tag
      @book.tags << @tag
    end
    respond_to do |format|
      format.html { redirect_to @book, notice: 'Tag was successfully added.' }
      format.json { render :show, status: :ok, location: @book }
    end
  end

  def remove_tag
    @tag_name = params.require(:book).permit(:tags)
    @tag = Tag.find_by(name: @tag_name[:tags])
    @book.tags.delete(@tag)
    respond_to do |format|
      format.html { redirect_to @book, notice: 'Tag was successfully removed.' }
      format.json { render :show, status: :ok, location: @book }
    end
  end

  def add_book
    new_book = Book.new
    new_book.name = @book.name
    new_book.author = @book.author
    new_book.document = @book.document
    new_book.image = @book.image
    new_book.description = @book.description
    new_book.access = "Private"
    if @book.tags.size != 0
      @book.tags.each do |t|
        new_book.tags << t
      end
    end
    current_user.books << new_book
    new_book.save
    redirect_to new_book, notice: 'Book was successfully added to your library.'
  end

  private
    # Use callbacks to share common setup or constraints between actions.
    def set_book
      @book = Book.find(params[:id])
    end

    def googleapi
      name = @book.name.dup
      name.sub! ' ', '+'
      query = "https://www.googleapis.com/books/v1/volumes?q=#{name}&maxResults=1&key=#{ENV['G_API_KEY']}"
      @resp = HTTParty.get(query)
      response = JSON.parse(@resp.body)
      @GoogleItem = response["items"][0]["volumeInfo"]
      @Grating = @GoogleItem['averageRating'].to_i
    end

    def imbdapi
      name = @book.name.dup
      name.sub! ' ', '+'
      query = "http://www.omdbapi.com/?t=#{name}&y=&plot=short&r=json"
      resp = HTTParty.get(query)
      @ImbdItem = JSON.parse(resp.body)
      @link = "http://www.imdb.com/title/" + @ImbdItem["imdbID"].to_s
      @Irating = ((@ImbdItem["imdbRating"].to_f)/2).round
    end

    def set_path
      @path = (Rails.root.to_s + "/public" + @book.document.url).split('?').first
    end


    # Never trust parameters from the scary internet, only allow the white list through.
    def book_params
      params.require(:book).permit(:name, :author, :document, :image, :description, :access ,:tags, :format)
    end
end

app/helpers/books_helper.rb
module BooksHelper
end

app/views/books/_form.html.erb
<style>
form {
  font-size: medium;
}
</style>

<%= form_for(@book, :html => {:multipart => true}) do |f| %>
  <% if @book.errors.any? %>
    <div id="error_explanation">
         <h2><%= pluralize(@book.errors.count, "error") %> prohibited this book from being saved:</h2>
         <ul>
        <% @book.errors.full_messages.each do |message| %>
          <li><%= message %></li>
        <% end %>
        </ul>
    </div>
  <% end %>

  <div class="field">
    <%= f.label :name, "Title*" %><br>
    <%= f.text_field :name %>
  </div>
  <br>
  <div class="field">
    <%= f.label :author, "Author*" %><br>
    <%= f.text_field :author %>
  </div>
  <br>
  <div class="field">
    <%= f.label :document, "Document*" %>
    <%= f.file_field :document %>
  </div>
  <br>
  <div class="field">
    <%= f.label :image %><br>
    <%= f.file_field :image %>
  </div>
  <br>
  <div class="text_area">
    <%= f.label :description %><br>
    <%= f.text_area :description, size: "40x2" %>
  </div>
  <br>
  <div class="field">
    <%= f.label :access, "Access*" %><br>
    <%= f.radio_button(:access, "Private") %>
    <%= f.label(:access_private, "Private") %><br>
    <%= f.radio_button(:access, "Public") %>
    <%= f.label(:access_public, "Public") %>
  </div>
  <br>
  <div class="actions">
    <%= f.submit class: "btn btn-lg btn-success" %>
  </div>
<% end %>

app/views/books/_pages.html.erb
<div class="col-md-1 col-xs-1">
    <%= link_to 'Back', @book, class: "btn btn btn-default pull-left", style: "margin-top: 15px;" %>
</div>
<div class="col-md-offset-2 col-md-6 col-xs-10 booktop">
    <center>
        <h1><%= @book.name %></h1>
        <h5>by <%= @book.author %></h5>
        <nav>
		  <ul class="pager">
		  	<% min = 100 %>
		  	<% if @data[@page-1].text.length < min %>
		  		<% if @data[@page-2].text.length < min %>
		  			<li class="previous"><%= link_to '<span aria-hidden="true">&laquo;</span> Previous'.html_safe, read_path(@book,@page-3), remote: true %></li>
		  		<% else %>
		  			<li class="previous"><%= link_to '<span aria-hidden="true">&laquo;</span> Previous'.html_safe, read_path(@book,@page-2), remote: true %></li>
		  		<% end %>
		  	<% else %>
		    	<li class="previous"><%= link_to '<span aria-hidden="true">&laquo;</span> Previous'.html_safe, read_path(@book,@page-1), remote: true %></li>
		    <% end %>
		    <% if @data[@page+1].text.length < min %>
		  		<% if @data[@page+2].text.length < min %>
		  			<li class="next"><%= link_to 'Next <span aria-hidden="true">&raquo;</span>'.html_safe, read_path(@book,@page+3), remote: true %></li>
		  		<% else %>
		  			<li class="next"><%= link_to 'Next <span aria-hidden="true">&raquo;</span>'.html_safe, read_path(@book,@page+2), remote: true %></li>
		  		<% end %>
		  	<% else %>
		    	<li class="next"><%= link_to 'Next <span aria-hidden="true">&raquo;</span>'.html_safe, read_path(@book,@page+1), remote: true %></li>
		    <% end %>
		  </ul>
		</nav>
    </center>
    <center>
           <h6><%= (@page).modulo(@data.count)+1%>/<%=@data.count%></h6>
    </center>
</div>
<div class="col-md-offset-3 col-md-6 col-xs-12">
    <pre id="book-read">
        <%= @data[@page] %>
    </pre>
</div>
<center>
    <div class="col-md-offset-3 col-md-6 col-xs-12 booktop">
        <nav>
		  <ul class="pager">
		  	<% if @data[@page-1].text.length < min %>
		  		<% if @data[@page-2].text.length < min %>
		  			<li class="previous"><%= link_to '<span aria-hidden="true">&laquo;</span> Previous'.html_safe, read_path(@book,@page-3), remote: true %></li>
		  		<% else %>
		  			<li class="previous"><%= link_to '<span aria-hidden="true">&laquo;</span> Previous'.html_safe, read_path(@book,@page-2), remote: true %></li>
		  		<% end %>
		  	<% else %>
		    	<li class="previous"><%= link_to '<span aria-hidden="true">&laquo;</span> Previous'.html_safe, read_path(@book,@page-1), remote: true %></li>
		    <% end %>
		    <% if @data[@page+1].text.length < min %>
		  		<% if @data[@page+2].text.length < min %>
		  			<li class="next"><%= link_to 'Next <span aria-hidden="true">&raquo;</span>'.html_safe, read_path(@book,@page+3), remote: true %></li>
		  		<% else %>
		  			<li class="next"><%= link_to 'Next <span aria-hidden="true">&raquo;</span>'.html_safe, read_path(@book,@page+2), remote: true %></li>
		  		<% end %>
		  	<% else %>
		    	<li class="next"><%= link_to 'Next <span aria-hidden="true">&raquo;</span>'.html_safe, read_path(@book,@page+1), remote: true %></li>
		    <% end %>
		  </ul>
		</nav>
    </div>
</center>

app/views/books/add_tag.html.erb
redirect_to @book

app/views/books/edit.html.erb
<div class="container">
	<div class="col-md-7">
		<div class="jumbotron">
			<h2>Editing Book</h2>

			<%= render 'form' %>
			<br>
			<%= link_to "Back", :back, class: "btn btn btn-default" %>
		</div>
	</div>
	<div class="col-md-5">
	</div>
</div> <!-- /container -->

app/views/books/index.html.erb
<div class="col-md-1">
</div>
<div class="col-md-10">
<p id="notice"><%= notice %></p>

<h1>Listing Books</h1>

<table>
  <thead>
    <tr>
      <th>Name</th>
      <th>Author</th>
      <th colspan="3"></th>
    </tr>
  </thead>

  <tbody>
    <% @books.each do |book| %>
      <tr>
        <td><%= book.name %></td>
        <td><%= book.author %></td>
        <% if book.document? %>
          <td><%= link_to book.document.url, book.document.url %></td>
          <%end%>
        <br>
        <td><%= link_to 'Show' , book %></td>
        <td><%= link_to 'Edit', edit_book_path(book) %></td>
        <td><%= link_to 'Delete', book, method: :delete, data: { confirm: 'Are you sure?' } %></td>
      </tr>
    <% end %>
  </tbody>
</table>

<br>

<%= link_to 'New Book', new_book_path %>
</div>
<div class="col-md-1">
</div>

app/views/books/new.html.erb
<div class="container">
	<div class="col-md-7">
		<div class="jumbotron">
			<h2>New Book</h2>

			<%= render 'form' %>
			<br>
			<%= link_to 'Back', home_path, class: "btn btn btn-default" %>
		</div>
	</div>
	<div class="col-md-5">
	</div>
</div> <!-- /container -->

app/views/books/read.html.erb
<div class="container" id="reader">
    <%= render 'pages' %>
</div>

app/views/books/read.js.erb
$('#reader').html("<%=j render 'pages' %>")

app/views/books/show.html.erb
<style>
  form {
    font-size: large;
  }
  #loadingDiv {
    background: #ffffff;
    color: #666666;
    z-index: 5000;
    text-align: center;
  }
</style>
<script>
  $('#load').click(function(){
   $('html').html("<br/><br/><br/><br/><br/><br/><br/><br/><br/><br/><br/><br/><br/><center><div id=loadingDiv><img src='http://www.animatedimages.org/data/media/53/animated-book-image-0018.gif' /><br/><p style='font-family: 'Helvetica Neue', Helvetica, Arial, sans-serif; font-size: 21px; font-weight: 200;'>Opening book, please wait...</p></div></center>"); 
});
</script>
<div class="container">

  <div class="col-md-7 col-sm-12">
    <div class="jumbotron">
      <p class="lead" id="notice"><%= notice %>
      </p>

      <p class="lead"  style="font-size:45px"><strong><%= @book.name %></strong>
      </p>

      <p class="lead" style="font-size:25px">by <strong><%= @book.author %></strong>
      </p>

      <p class="lead">
        <% if @book.tags.size != 0 %>
          <% @book.tags.each do |f| %>
            <strong><a style="color:<%=f.color%>" href="/tags"><span class="glyphicon glyphicon-tag"></span> <%=f.name%> </a></strong>
          <% end %>
          <br/>
        <% end %>
      </p>

      <p class="lead">
        <%= link_to 'Read', read_path(@book,0), class: "btn btn-lg btn-success", id: "load" %>
        <td><%= link_to '<span class="glyphicon glyphicon-send"></span> Send'.html_safe, email_book_path, data: { confirm: 'Are you sure?' }, class: "btn btn-lg btn-primary" %></td>
      </p>

      <p class="lead">
        Current file format: <%= @book.document_file_name.split(".").last %>
        <%= form_for @book, url: {action: "convert"} do |f| %>
          <label class="lead">Convert and download file in:  </label>
          <select type="text" name="book[format]" id="book_format">
            <option value="pdf" class="lead">PDF</option>
            <option value="epub" class="lead">EPUB</option>
            <option value="mobi" class="lead">MOBI</option>
          </select>
          <button type="submit" class="btn btn-default"><span class="glyphicon glyphicon-transfer"></span> Convert</button>
        <% end %>

      <% if @book.access != 'Public' %>
          <% if current_user.tags.size == 0 %>
            <div class="alert alert-danger" role="alert">
              <strong>You don't have Tags to asign!</strong> Try to <%= link_to('create', new_tag_path) %> Tags.
            </div>
          <% else %>
            <% if @book.user != nil %>
              <%= form_for @book, url: {action: "add_tag"} do |f| %>
                <label class="lead">Select tag to add: </label>
                <select type="text" name="book[tags]" id="book_tags">
                  <% @book.user.tags.each do |f| %>
                    <option class="lead"><%=f.name%></option>
                  <% end %>
                </select>
                <button type="submit" class="btn btn-default"><span class="glyphicon glyphicon-tag"></span> Add tag</button>
              <% end %>
            <% end %>
          <% end %>
          <% if @book.tags.size != 0 %>
            <%= form_for @book, url: {action: "remove_tag"} do |f| %>
              <label class="lead">Select tag to remove: </label>
              <select type="text" name="book[tags]" id="book_tags">
                <% @book.tags.each do |f| %>
                  <option class="lead"><%=f.name%></option>
                <% end %>
              </select>
              <button type="submit" class="btn btn-default"><span class="glyphicon glyphicon-tag"></span> Remove tag</button>
            <% end %>
          <% end %>
        </p>
      <% end %>

      <p class="lead">
        <%= link_to '<span class="glyphicon glyphicon-pencil"></span> Edit'.html_safe, edit_book_path(@book), class: "btn btn-warning" %>
        <%= link_to '<span class="glyphicon glyphicon-trash"></span> Delete'.html_safe, @book, method: :delete, data: { confirm: 'Are you sure?' }, class: "btn btn-danger" %>
        <% if @book.document? %>
          <%= link_to '<span class="glyphicon glyphicon-download-alt"></span> Download file'.html_safe, @book.document.url, class: "btn btn-default" %>
        <%end%>
        <%= link_to '<span class="glyphicon glyphicon-arrow-left"></span> Back'.html_safe, home_path , class: "btn btn-default"%>
      </p>
    </div>
  </div>

  <div class="col-md-5 col-sm-12">

    <p class="lead">
      <strong>Links:</strong>
    </p>

    <div class="row lead col-md-12 col-sm-12">
      <!--  GOOGLE LINK  -->
      <div class="col-md-offset-1 col-md-5 col-xs-6">
        <center><a href=<%=@GoogleItem["previewLink"].to_str%> target="_blank"><img src="https://cdn4.iconfinder.com/data/icons/new-google-logo-2015/400/new-google-favicon-128.png"></a></center>
        <% if @GoogleItem.has_key?("averageRating") %>
          <center><p class="lead">
          <% for i in 1..@Grating %>
            &#x2605;
          <%end%>
          <% for i in 1..(5-@Grating) %>
            &#x2606;
          <%end%>
          </p></center>
        <%else%>
          <center><p class="lead">No Rating</p></center>
        <%end%>
      </div>
      <!--  IMDB LINK  -->
      <div class="col-md-offset-1 col-md-5 col-xs-6">
        <% if @ImbdItem["Response"] == "True"%>
          <center><a href=<%=@link%> target="_blank"><img src="http://icons.iconarchive.com/icons/chrisbanks2/cold-fusion-hd/128/imdb-2-icon.png"></a></center>
          <% if @ImbdItem.has_key?("imdbRating") %>
           <center><p class="lead">
            <% for i in 1..@Irating %>
              &#x2605;
            <%end%>
            <% for i in 1..(5-@Irating) %>
              &#x2606;
            <%end%>
            </p></center>
          <%else%>
            <center><p class="lead">No Rating</p></center>
          <%end%>
        <% end %>
      </div>
    </div>

    <% if @GoogleItem.has_key?("description")%>
      <h4>Google Books Description:</h4>
      <p><%=@GoogleItem["description"]%></p>
    <% end %>
  </div>

</div> <!-- /container -->