config/routes.rb
Rails.application.routes.draw do
  resources :tags
  devise_for :users, controllers: {registrations: 'users/registrations'}

  resources :books, except: :index
  resources :tags, except: :show

  get '/books/:id/read/:page(.:format)' => 'books#read', as: 'read'
  root 'pages#main'
  get 'home' => 'pages#home'
  get 'adm_users' => 'pages#adm_users'
  get 'error' => 'pages#error'
  get 'private' => 'pages#private'
  get 'delete_user' => 'pages#delete_user'
  get 'feedback' => 'pages#feedback'

  get '/books/:id/send_book' => 'books#email_book', as: 'email_book'

  get 'publiclib' => 'pages#publiclib'

  patch 'books/:id/convert(.:format)' => 'books#convert', as: 'convert'
  patch 'books/:id/add_tag(.:format)' => 'books#add_tag', as: 'add_tag'
  patch 'books/:id/remove_tag(.:format)' => 'books#remove_tag', as: 'remove_tag'
  post 'books/:id(.:format)' => 'books#add_book', as: 'add_book'

end

app/models/tag.rb
class Tag < ActiveRecord::Base
	validates :name, presence: true
	validates :color, presence: true
	belongs_to :user
	has_and_belongs_to_many :books
end

app/controllers/tags_controller.rb
class TagsController < ApplicationController
  before_action :set_tag, only: [:show, :edit, :update, :destroy]
  before_action :authenticate_user!

  # GET /tags
  # GET /tags.json
  def index
    @tags = Tag.all
  end

  # GET /tags/1
  # GET /tags/1.json
  def show
  end

  # GET /tags/new
  def new
    @tag = Tag.new
  end

  # GET /tags/1/edit
  def edit
  end

  # POST /tags
  # POST /tags.json
  def create
    @tag = Tag.new(tag_params)
    current_user.tags << @tag

    respond_to do |format|
      if @tag.save
        format.html { redirect_to tags_path, notice: 'Tag was successfully created.' }
      else
        format.html { render :new }
        format.json { render json: @tag.errors, status: :unprocessable_entity }
      end
    end
  end

  # PATCH/PUT /tags/1
  # PATCH/PUT /tags/1.json
  def update
    respond_to do |format|
      if @tag.update(tag_params)
        format.html { redirect_to tags_path, notice: 'Tag was successfully updated.' }
      else
        format.html { render :edit }
        format.json { render json: @tag.errors, status: :unprocessable_entity }
      end
    end
  end

  # DELETE /tags/1
  # DELETE /tags/1.json
  def destroy
    @tag.delete
    respond_to do |format|
      format.html { redirect_to tags_url, notice: 'Tag was successfully deleted.' }
      format.json { head :no_content }
    end
  end

  private
    # Use callbacks to share common setup or constraints between actions.
    def set_tag
      @tag = Tag.find(params[:id])
    end

    # Never trust parameters from the scary internet, only allow the white list through.
    def tag_params
      params.require(:tag).permit(:name, :color)
    end
end

app/helpers/tags_helper.rb
module TagsHelper
end

app/views/tags/_form.html.erb
<style>
form {
  font-size: medium;
}
</style>

<%= form_for(@tag) do |f| %>
  <% if @tag.errors.any? %>
    <div id="error_explanation">
         <h2><%= pluralize(@tag.errors.count, "error") %> prohibited this tag from being saved:</h2>
         <ul>
        <% @tag.errors.full_messages.each do |message| %>
          <li><%= message %></li>
        <% end %>
        </ul>
    </div>
  <% end %>
<br>
  <div class="field">
    <%= f.label :name, "Name*" %><br>
    <%= f.text_field :name %>
  </div>

<br>
  <div class="field">
    <%= f.label :color, "Color*" %><br>
    <%= f.color_field :color %>
  </div>

<br>
  <div class="actions">
    <%= f.submit class: "btn btn-lg btn-success"%>
  </div>

<% end %>

app/views/tags/edit.html.erb
<div class="container">
	<div class="col-md-5">
		<div class="jumbotron">
			<h2>Editing Tag</h2>
			<%= render 'form' %>
			<br>
			<%= link_to "Back", :back, class: "btn btn btn-default" %>
		</div>
	</div>
	<div class="col-md-7">
	</div>
</div> <!-- /container -->

app/views/tags/index.html.erb
<style>
table {
  font-size: large;
}
</style>
<div class="container">
  <div class="col-md-7">
    <div class="jumbotron">
      <p class="lead" id="notice"><%= notice %></p>
      <% if current_user.email != 'bookstreammailer@gmail.com' %>
        <h2>Your Tags</h2>
      <% else %>
        <h2>All Tags of BookStream Users</h2>
      <% end %>
      <br>
      <table style="width: 90%">
        <thead>
          <tr>
            <th>Name</th>
            <% if current_user.email == 'bookstreammailer@gmail.com' %>
              <th>Owner</th>
            <% end %>
            <th colspan="3"></th>
          </tr>
        </thead>
        <tbody>
          <% @tags.each do |tag| %>
            <tr>
            <% if current_user.email != 'bookstreammailer@gmail.com' %>
              <% if current_user.tags.include? tag %>
                <td style="color:<%=tag.color%>"><span class="glyphicon glyphicon-tags"></span> <%= tag.name %></td>
                <td><%= link_to '<span class="glyphicon glyphicon-pencil"></span>'.html_safe, edit_tag_path(tag), class: "btn btn-warning btn-sm", style: "margin-bottom:5px;margin-top:5px" %></td>
                <td><%= link_to '<span class="glyphicon glyphicon-trash"></span>'.html_safe, tag, method: :delete, data: { confirm: 'Are you sure?' }, class: "btn btn-danger btn-sm", style: "margin-bottom:5px;margin-top:5px" %></td>
              <% end %>
            <% else %>
              <td style="color:<%=tag.color%>"><span class="glyphicon glyphicon-tags"></span> <%= tag.name %></td>
              <% if tag.user != nil %>
                <td><%= tag.user.name %> <%= tag.user.last_name %></td>
              <% else %>
                <td>User does not exist anymore</td>  
              <% end %>            
              <td><%= link_to '<span class="glyphicon glyphicon-pencil"></span>'.html_safe, edit_tag_path(tag), class: "btn btn-warning btn-sm", style: "margin-bottom:5px;margin-top:5px" %></td>
              <td><%= link_to '<span class="glyphicon glyphicon-trash"></span>'.html_safe, tag, method: :delete, data: { confirm: 'Are you sure?' }, class: "btn btn-danger btn-sm", style: "margin-bottom:5px;margin-top:5px" %></td>
            <% end %>
            </tr>     
          <% end %>
        </tbody>
      </table>
      <br>
      <br>
      <%= link_to 'New Tag', new_tag_path, class: "btn btn-success" %>
      <br>
      <br>
      <%= link_to "Back", :back, class: "btn btn btn-default" %>
    </div>
  </div>
</div> <!-- /container -->

app/views/tags/new.html.erb
<div class="container">
	<div class="col-md-5">
		<div class="jumbotron">
			<h2>New Tag</h2>
			<%= render 'form' %>
			<br>
			<%= link_to "Back", :back, class: "btn btn btn-default" %>
		</div>
	</div>
	<div class="col-md-7">
	</div>
</div> <!-- /container -->